language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_success: |
  mv target/doc . &&
  (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
env:
  global:
  - secure: PFa5ypdXegba1AdlskgbVvsl1YSnfUjHup9M5WmwALKukF80qaU5OMF4eGGLfnGBXWhWWYdM5C8CEpXqHRv/KxHBm5/oVxteUPwoRt7FCF6DL/E/Johw31vxCwmjmthOE0OxbX+99NNBszOsYx7vkuCmxA7WmW5UGFG7afZJc4I=
notifications:
  on_success: never
